### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TechInterMezzo** [bfs18/rfwave#5]
What is the license for this project?

**Comment by bfs18** [comment]
Hi @TechInterMezzo Thank you for your interest. The code is provided under the terms of the MIT License, which permits reuse, modification, and distribution for any purpose, without any restrictions and without warranty of any kind. While not required, I would appreciate attribution by citing my paper if my work has contributed to your project.

**Comment by TechInterMezzo** [comment]
Thank you for the answer and your work.
I would suggest to put a LICENSE.md with the MIT license text into the repository, so that everybody can see it.
